GO
DROP TABLE CLIENTE
GO
CREATE TABLE CLIENTE
(
CLI_CODIGO	INTEGER		NOT NULL	PRIMARY KEY	,
CLI_DESCRI	VARCHAR(60)	NULL				,

CLI_CPF		 VARCHAR(15)	NULL		,
CLI_ENDERE	 VARCHAR(80)	NULL		,
CLI_NUMERO	 VARCHAR(08)	NULL		,
CLI_CIDADE	 VARCHAR(30)	NULL		,
CLI_BAIRRO	 VARCHAR(30)	NULL		,
CLI_CEP		 VARCHAR(10)	NULL		,
CLI_ESTADO	 VARCHAR(02)	NULL		,
CLI_TELEFONE VARCHAR(15)	NULL		,
CLI_CELULAR	 VARCHAR(15)	NULL		,
CLI_DATA	 VARCHAR(10)	NULL		
)
