GO
DROP PROCEDURE CLIENTE_SP_SEL
GO
CREATE PROCEDURE CLIENTE_SP_SEL
(
@INP_CODIGO	INTEGER		,
@INP_DESCRI	VARCHAR(80)	,
@INP_CPF	VARCHAR(15)	
)

WITH ENCRYPTION 
AS

	
	IF	@INP_DESCRI	IS	NULL				SELECT	@INP_DESCRI	=	''
	IF	@INP_CPF	=	'   .   .   -  ' 	SELECT	@INP_CPF	=	''


	SELECT	CLI_CODIGO	,
			CLI_DESCRI	,
			CLI_CPF	
	FROM CLIENTE


	WHERE(((@INP_CODIGO	=	0)	AND	(CLI_CODIGO	>	0))		OR
		 ((@INP_CODIGO  <>	0)	AND	(CLI_CODIGO	=	@INP_CODIGO)))	
												AND
		
		(((@INP_DESCRI	=	'')	AND	(CLI_CODIGO	>	0))		OR
		 ((@INP_DESCRI	<>	'')	AND	(CLI_DESCRI LIKE '%'+@INP_DESCRI+'%')))	
												AND

		(((@INP_CPF	=	'')		AND	(CLI_CODIGO	>	0))		OR
		 ((@INP_CPF	<>	'')		AND	(CLI_CPF	=	@INP_CPF)))	


RETURN