GO
DROP PROCEDURE ENDERECO_SP_SEL
GO
CREATE PROCEDURE ENDERECO_SP_SEL
(
@INP_CEP	VARCHAR(09)	,
@INP_ESTADO	VARCHAR(03)	,
@INP_ENDERECO	VARCHAR(120)	
)

WITH ENCRYPTION 
AS


	IF	@INP_CEP	IS	NULL	SELECT	@INP_CEP	=	' '
	IF	@INP_ENDERECO	IS	NULL	SELECT	@INP_ENDERECO	=	' '
	
	SELECT
		END_CEP		,
		END_UF 		,
		END_BAIRRO 	,
		END_CIDADE 	,
		END_ENDERECO 	

	FROM ENDERECO	WITH(NOLOCK)

	WHERE	(
		((@INP_CEP		=	' ')	AND	(END_CEP	<>	'TOT'))			OR
		((@INP_CEP		<>	' ')	AND	(END_CEP	=	@INP_CEP))
		)												AND

		
		(
		((@INP_ESTADO		=	'TOT'	   ) 	AND	(END_CEP	<>	'TOT'))		OR
		 ((@INP_ESTADO		<>	'TOT'	   )	AND	(END_UF		=	@INP_ESTADO))
		)												AND	


		
		
		(
		((@INP_ENDERECO		=	' '	) 	AND	(END_ENDERECO	<>	'ZZZZZ'))	OR
		((@INP_ENDERECO		<>	' '	)	AND	(END_ENDERECO	LIKE	'%' + @INP_ENDERECO + '%' ))
		)

		

	
	ORDER BY END_CEP	


RETURN