GO
DROP TABLE ENDERECO
GO
CREATE TABLE ENDERECO 
(
END_CEP			VARCHAR(09)		NOT NULL PRIMARY KEY	,
END_UF 			VARCHAR(02)		NOT NULL		,	
END_BAIRRO 		VARCHAR(80)		NOT NULL		,
END_CIDADE 		VARCHAR(80)		NOT NULL		,
END_ENDERECO 	VARCHAR(120)	NOT NULL		
)