GO
DROP PROCEDURE INGREDIENTES_SP_CON
GO
CREATE PROCEDURE INGREDIENTES_SP_CON
(
@INP_CODIGO	INTEGER	
)

WITH ENCRYPTION 
AS
	
	IF	@INP_CODIGO	IS	NULL	SELECT	@INP_CODIGO	=	0


	SELECT	ING_CODIGO		,
			ING_DESCRICAO	,
			ING_VALOR		,
			ING_IMAGEM		,
			ING_LANCHE		

	FROM INGREDIENTES	WITH(NOLOCK)

	WHERE	(((@INP_CODIGO		=	0)	AND	(ING_CODIGO	<>	0))	OR
			((@INP_CODIGO		<>	0)	AND	(ING_CODIGO	=	@INP_CODIGO)))


	
	ORDER BY ING_CODIGO	
