GO
DROP PROCEDURE INGREDIENTES_SP_SEL
GO
CREATE PROCEDURE INGREDIENTES_SP_SEL
(
@INP_CODIGO	INTEGER,
@INP_DESCRI	VARCHAR(60)
)

WITH ENCRYPTION 
AS

	
	IF	@INP_CODIGO	IS	NULL	SELECT	@INP_DESCRI	=	0
	IF	@INP_DESCRI	IS	NULL	SELECT	@INP_DESCRI	=	''


	SELECT	ING_CODIGO		,
			ING_DESCRICAO	,
			ING_VALOR		,
			ING_IMAGEM

	FROM INGREDIENTES	WITH(NOLOCK)

	WHERE(
		((@INP_CODIGO  =	0)	AND	(ING_CODIGO	<>	0))		OR
		((@INP_CODIGO  <>	0)	AND	(ING_CODIGO	=	@INP_CODIGO))
		)	
																	AND		
		(
		((@INP_DESCRI	=	'')	AND	(ING_CODIGO	<>	'ZZZ'))			OR
		 ((@INP_DESCRI	<>	'')	AND	(ING_DESCRICAO LIKE '%'+@INP_DESCRI+'%'))
		 )


	ORDER BY ING_CODIGO

RETURN
