GO
DROP TABLE LANCHEINGR
GO
CREATE TABLE LANCHEINGR
(
LAN_CODIGO	INTEGER NOT NULL	,
LIN_ITEM	INTEGER	NOT NULL	,
ING_CODIGO	INTEGER	NOT NULL	,
LIN_VALOR	FLOAT	NOT NULL DEFAULT(0)
)

ALTER TABLE LANCHEINGR ADD CONSTRAINT [PK_LANCHEINGR_LAN_CODIGO_ITEM_INGCOD] PRIMARY KEY (LAN_CODIGO,LIN_ITEM,ING_CODIGO)


INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,1,1,10.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,2,2,2
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,3,3,5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,4,4,3
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,5,5,2.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,6,6,1.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,7,7,1
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 1,8,8,7.5

INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,1,1,10.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,2,2,2
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,3,3,5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,4,6,1.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,5,7,1
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 2,6,5,2.5

INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,1,1,10.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,2,2,2
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,3,3,5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,4,4,3
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,5,6,1.5
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,6,7,1
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 3,7,8,7.5

INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 4,1,9,8
INSERT INTO LANCHEINGR(LAN_CODIGO,LIN_ITEM,ING_CODIGO,LIN_VALOR) SELECT 4,2,10,4.5