GO
DROP PROCEDURE LANCHES_SP_SEL
GO
CREATE PROCEDURE LANCHES_SP_SEL
(
@INP_CODIGO	INTEGER,
@INP_DESCRI	VARCHAR(60)
)

WITH ENCRYPTION 
AS

	
	IF	@INP_CODIGO	IS	NULL	SELECT	@INP_DESCRI	=	0
	IF	@INP_DESCRI	IS	NULL	SELECT	@INP_DESCRI	=	''


	SELECT	LAN_CODIGO	,
			LAN_DESCRICAO	,
			LAN_VALORTOTAL

	FROM LANCHES	WITH(NOLOCK)

	WHERE(
		((@INP_CODIGO  =	0)	AND	(LAN_CODIGO	<>	0))		OR
		((@INP_CODIGO  <>	0)	AND	(LAN_CODIGO	=	@INP_CODIGO))
		)	
																	AND		
		(
		((@INP_DESCRI	=	'')	AND	(LAN_CODIGO	<>	'ZZZ'))			OR
		 ((@INP_DESCRI	<>	'')	AND	(LAN_DESCRICAO LIKE '%'+@INP_DESCRI+'%'))
		 )


	ORDER BY LAN_CODIGO

RETURN
