GO
DROP PROCEDURE LANCHEINGR_SP_SEL
GO
CREATE PROCEDURE LANCHEINGR_SP_SEL
(
	@INP_LANCHE		INTEGER
)

WITH ENCRYPTION 
AS


	SELECT	LAN_CODIGO	,
			LIN_ITEM	,
			ING_CODIGO	,
			(SELECT ING_DESCRICAO   FROM INGREDIENTES ING WHERE ING.ING_CODIGO = LANCHEINGR.ING_CODIGO) ING_DESCRI,
			(SELECT ING.ING_IMAGEM  FROM INGREDIENTES ING WHERE ING.ING_CODIGO = LANCHEINGR.ING_CODIGO) ING_IMAGEM,
			LIN_VALOR	

	FROM LANCHEINGR	WITH(NOLOCK)


	WHERE	LAN_CODIGO		=	@INP_LANCHE

	
	ORDER BY LAN_CODIGO	,
			 LIN_ITEM	,
			 ING_CODIGO