GO
DROP PROCEDURE LANCHES_SP_CON
GO
CREATE PROCEDURE LANCHES_SP_CON
(
@INP_CODIGO	INTEGER	
)

WITH ENCRYPTION 
AS
	
	IF	@INP_CODIGO	IS	NULL	SELECT	@INP_CODIGO	=	0


	SELECT	LAN_CODIGO		,
			LAN_DESCRICAO	,
			LAN_VALORTOTAL	,
			LAN_IMAGEM

	FROM LANCHES	WITH(NOLOCK)

	WHERE	(((@INP_CODIGO		=	0)	AND	(LAN_CODIGO	<>	0))	OR
			((@INP_CODIGO		<>	0)	AND	(LAN_CODIGO	=	@INP_CODIGO)))	

	
	ORDER BY LAN_CODIGO	
