GO
DROP TABLE LANCHES
GO
CREATE TABLE LANCHES
(
	LAN_CODIGO		INTEGER			NOT NULL PRIMARY KEY	,
	LAN_DESCRICAO	VARCHAR(50)		NOT NULL				,
	LAN_VALORTOTAL	FLOAT			NOT NULL DEFAULT(0)		,
	LAN_IMAGEM		VARCHAR(200)	NULL
)


INSERT INTO LANCHES(LAN_CODIGO,LAN_DESCRICAO,LAN_VALORTOTAL) SELECT 1,'X TUDO',33
INSERT INTO LANCHES(LAN_CODIGO,LAN_DESCRICAO,LAN_VALORTOTAL) SELECT 2,'X SALADA',22.5
INSERT INTO LANCHES(LAN_CODIGO,LAN_DESCRICAO,LAN_VALORTOTAL) SELECT 3,'X BACON',30.5
INSERT INTO LANCHES(LAN_CODIGO,LAN_DESCRICAO,LAN_VALORTOTAL) SELECT 4,'CACHORRO QUENTE',12.5