GO
DROP PROCEDURE PEDADICIONAL_SP_CON
GO
CREATE PROCEDURE PEDADICIONAL_SP_CON
(
	@INP_PEDIDO	INTEGER	
)

WITH ENCRYPTION
AS

	SELECT	PED_CODIGO	,
			PEA_ITEM	,
			ING_CODIGO	,
			PEA_VALOR	,
			(SELECT ING_DESCRICAO FROM INGREDIENTES ING WHERE ING.ING_CODIGO = PEA.ING_CODIGO) ING_DESCRI		

	FROM	PEDADICIONAL PEA
	WHERE	PED_CODIGO		=	@INP_PEDIDO			


	ORDER BY	PED_CODIGO	,
				PEA_ITEM	