GO
DROP TABLE PEDIDO
GO
CREATE TABLE PEDIDO
(
	PED_CODIGO		INTEGER		NOT NULL PRIMARY KEY,
	CLI_CODIGO		INTEGER		NOT NULL			,
	PED_DATA		VARCHAR(15)	NOT NULL			,
	PED_DESCONTO	FLOAT		NOT NULL DEFAULT(0)	,
	PED_VALOR		FLOAT		NOT NULL DEFAULT(0)
)

GO
DROP TABLE PEDLANCHE
GO
CREATE TABLE PEDLANCHE
(
	PED_CODIGO		INTEGER		NOT NULL	,
	PED_ITEM		INTEGER		NOT NULL	,
	LAN_CODIGO		INTEGER		NOT NULL	,			
	PED_VALOR		FLOAT		NOT NULL	DEFAULT(0)		
	
)

ALTER TABLE PEDLANCHE ADD CONSTRAINT [PK_PEDLANCHE_PED_CODIGO_ITEM] PRIMARY KEY (PED_CODIGO,PED_ITEM)


GO
DROP TABLE PEDLANCHEITENS
GO
CREATE TABLE PEDLANCHEITENS
(
	PED_CODIGO		INTEGER		NOT NULL	,
	PED_ITEM		INTEGER		NOT NULL	,	
	ING_CODIGO		INTEGER		NOT NULL	,
	ING_ITEM		INTEGER		NOT NULL	,
	PED_VALOR		FLOAT		NOT NULL	DEFAULT(0)		
	
)

ALTER TABLE PEDLANCHEITENS ADD CONSTRAINT [PK_PEDLANCHEITENS_PEDCODIGO_ITEM_INGCODIGO_INGITEM] PRIMARY KEY (PED_CODIGO,PED_ITEM,ING_CODIGO,ING_ITEM)


GO
DROP TABLE PEDADICIONAL
GO
CREATE TABLE PEDADICIONAL
(
	PED_CODIGO		INTEGER		NOT NULL	,
	PEA_ITEM		INTEGER		NOT NULL	,
	ING_CODIGO		INTEGER		NOT NULL	,			
	PEA_VALOR		FLOAT		NOT NULL	DEFAULT(0)		
	
)

ALTER TABLE PEDADICIONAL ADD CONSTRAINT [PK_PEDADICIONAL_PEDCODIGO_ITEM] PRIMARY KEY (PED_CODIGO,PEA_ITEM)