GO
DROP PROCEDURE PEDIDO_SP_CON
GO
CREATE PROCEDURE PEDIDO_SP_CON
(
@INP_CODIGO		INTEGER	,	
@INP_CLIENTE	INTEGER
)

WITH ENCRYPTION 
AS
	
	IF	@INP_CODIGO		IS	NULL	SELECT	@INP_CODIGO		=	0
	IF	@INP_CLIENTE	IS	NULL	SELECT	@INP_CLIENTE	=	0


	SELECT	PED_CODIGO	,
			CLI_CODIGO	,
			(SELECT CLI.CLI_DESCRI FROM CLIENTE CLI WHERE CLI.CLI_CODIGO = PED.CLI_CODIGO) CLI_DESCRI ,
			PED_DATA	,
			PED_VALOR	,
			PED_DESCONTO

	FROM	PEDIDO PED
	WHERE	(((@INP_CODIGO		=	0)	AND	(PED.PED_CODIGO	<>	0))	OR
			((@INP_CODIGO		<>	0)	AND	(PED.PED_CODIGO	=	@INP_CODIGO)))	

	  AND	(((@INP_CLIENTE		=	0)	AND	(PED.PED_CODIGO	<>	0))	OR
			((@INP_CLIENTE		<>	0)	AND	(PED.CLI_CODIGO	=	@INP_CLIENTE)))	

	
	ORDER BY PED_CODIGO	
