GO
DROP PROCEDURE PEDLANCHEITENS_SP_CON
GO
CREATE PROCEDURE PEDLANCHEITENS_SP_CON
(
	@INP_PEDIDO	INTEGER	,
	@INP_ITEM	INTEGER	
)

WITH ENCRYPTION
AS

	SELECT	PED_CODIGO	,
			PED_ITEM	,
			ING_CODIGO	,
			(SELECT ING_DESCRICAO FROM INGREDIENTES ING WHERE ING.ING_CODIGO = PED.ING_CODIGO) ING_DESCRI,
			ING_ITEM	,
			PED_VALOR	

	FROM	PEDLANCHEITENS PED
	WHERE	PED_CODIGO		=	@INP_PEDIDO		AND
			PED_ITEM		=	@INP_ITEM