GO
DROP PROCEDURE PEDLANCHE_SP_CON
GO
CREATE PROCEDURE PEDLANCHE_SP_CON
(
@INP_CODIGO		INTEGER
)

WITH ENCRYPTION 
AS

SELECT	PED_CODIGO	,
		PED_ITEM	,
		LAN_CODIGO	,
		(SELECT LAN_DESCRICAO FROM LANCHES LAN WHERE  LAN.LAN_CODIGO = PEDLANCHE.LAN_CODIGO) LAN_DESCRI	,
		PED_VALOR

FROM	PEDLANCHE
WHERE	PED_CODIGO	=	@INP_CODIGO


RETURN