GO
DROP PROCEDURE USUARIO_SP_SEL
GO
CREATE PROCEDURE USUARIO_SP_SEL
(
@INP_SIGLA	VARCHAR(03)	,
@INP_DESCRI	VARCHAR(60)
)

WITH ENCRYPTION 
AS

	IF	@INP_SIGLA	IS	NULL	SELECT	@INP_SIGLA	=	''
	IF	@INP_DESCRI	IS	NULL	SELECT	@INP_DESCRI	=	''


	SELECT	USU_SIGLA	,
			USU_NOME

	FROM USUARIO

	WHERE	(
		((@INP_SIGLA  =		'')	AND	(USU_SIGLA	<>	'ZZZ'))		OR
		((@INP_SIGLA  <>	'')	AND	(USU_SIGLA	=	@INP_SIGLA)))	
												AND
		
		(((@INP_DESCRI	=	' ')	AND	(USU_SIGLA	<>	'ZZZ'))		OR
		 ((@INP_DESCRI	<>	' ')	AND	(USU_NOME LIKE '%'+@INP_DESCRI+'%')))

	ORDER BY USU_NOME

RETURN

