GO
DROP TABLE USUARIO
GO
CREATE TABLE USUARIO
(
USU_SIGLA	VARCHAR(03)	NOT NULL	PRIMARY KEY	,
USU_NOME	VARCHAR(60)	NULL				,

USU_CPF		VARCHAR(18)	NULL		,
USU_RG		VARCHAR(15)	NULL		,
USU_ENDERE	VARCHAR(80)	NULL		,
USU_NUMERO	VARCHAR(08)	NULL		,
USU_CIDADE	VARCHAR(30)	NULL		,
USU_BAIRRO	VARCHAR(30)	NULL		,
USU_CEP		VARCHAR(10)	NULL		,
USU_ESTADO	VARCHAR(02)	NULL		,
USU_TELEFONE	VARCHAR(15)	NULL	,
USU_CELULAR	VARCHAR(15)	NULL		,
USU_DATNAS	DATETIME	NULL		,

USU_EMAIL	VARCHAR(50)	NULL		,
USU_CONTATO	VARCHAR(20)	NULL		,
USU_TELCONTATO	VARCHAR(15)	NULL		,

USU_SENHA	VARCHAR(15)	NULL		
)


INSERT INTO USUARIO
(
usu_sigla	,
usu_senha	,
usu_nome	
)
select	
'FX'	,
'FOXCONN'	,
'FOXCONN PRINCIPAL'


INSERT INTO USUARIO
(
usu_sigla	,
usu_senha	,
usu_nome	
)
select	
'FT'	,
'FOXCONN'	,
'FOXCONN SEGUNDARIO'
